kind: ConfigMap
apiVersion: v1
metadata:
  name: charon
data:
  CHARON_CLIENT_0_WILDCARDS: |
    http://localhost:3000,
    https://egapro-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_0_PROVIDER: github
  CHARON_CLIENT_1_WILDCARDS: |
    http://localhost:3000,
    https://egapro-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_1_PROVIDER: moncompteprotest
  CHARON_CLIENT_2_WILDCARDS: |
    http://localhost:3000,
    https://egapro-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_2_PROVIDER: moncomptepro
  CHARON_CLIENT_3_WILDCARDS: |
    http://localhost:3000,
    https://egapro-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_3_PROVIDER: fabriqueKeycloak
  CHARON_CLIENT_4_WILDCARDS: |
    http://localhost:3000,
    https://egapro-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_4_PROVIDER: proconnecttest
  CHARON_CLIENT_5_WILDCARDS: |
    http://localhost:3000,
    https://egapro-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_5_PROVIDER: proconnect
  CHARON_PUBLIC_HOST: https://egapro-charon.ovh.fabrique.social.gouv.fr
